/**
 * @file nx_screen.h
 * @brief Nextion master screen device abstraction layer.
 * @note Root container managing the entire application layout, page routing, and HAL link.
 * @copyright Copyright (c) 2026 Jacobo Gonzalez
 * @license MIT License
 */

#ifndef NX_SCREEN_H
#define NX_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "nx_types.h"
#include "nx_page.h"

/**
 * @brief Master Screen Device structure.
 * Orchestrates the active page state and binds the underlying communication drivers.
 */
struct NX_Screen
{
    NX_Page_t **pages;                      // Array of pointers to all pages in the project
    NX_Page_t *currentPage;                 // Pointer to the currently active page on display
    uint8_t pageCount;                      // Total number of pages compiled in the UI
    NX_Transport_t *transport;              // Transport driver
    NX_EventCallback_fnc globalEvent;       // Pointer to callback, global event drive
    
};

/*============================================================================*
 * Master Screen API Layer
 *============================================================================*/

/**
 * @brief Registers a hardware screen instance and links its page tree topology.
 * @param[out] screen Pointer to the uninitialized screen structure.
 * @param[in] pages Array of compiled page pointers (typically autogenerated).
 * @param[in] pageCount Number of pages inside the array.
 * @param[in] port Hardware port identifier token.
 * @return true if initialization parameters were legal, false otherwise.
 */
bool NX_ScreenInit(NX_Screen_t *screen, NX_Page_t **pages, uint8_t pageCount, NX_PortComm_ID_t port);

/**
 * @brief dispatches a hardware active page state update.
 * @param[in,out] screen Pointer to the master screen structure.
 * @param[in] pageId The newly triggered page identifier from the UART event.
 */
void NX_ScreenSetActivePage(NX_Screen_t *screen, uint8_t pageId);


#ifdef __cplusplus
}
#endif

#endif /* NX_SCREEN_H */
