/**
 * @file nx_object.h
 * @brief Nextion concrete object runtime instances and strict callback definitions.
 * @note Binds abstract component classes with physical screen instances safely
 *       by leveraging globally shared types from nx_types.h.
 * @copyright Copyright (c) 2026 Jacobo Gonzalez
 * @license MIT License
 */

#ifndef NX_OBJECT_H
#define NX_OBJECT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "nx_types.h"
#include "nx_component.h"
#include "nx_attributes.h"

/**
 * @brief Concrete Object Instance structure.
 * Represents a live component rendered on a specific Nextion page layout.
 * @note The type definition 'NX_Object_t' is centraly declared in nx_types.h.
 */
struct NX_Object
{
    // --- Metaclass Binding ---
    const NX_ComponentClass_t *component;   // Pointer to the immutable capability blueprint

    // --- Hard-Coded Screen Identifiers (Typically Autogenerated via Python tooling) ---
    uint8_t pageId;                         // The numeric index of the page holding this object
    uint8_t componentId;                    // The internal Nextion identifier index (ID) for this object
    NX_String_t objectName;                   // Literal alphanumeric string name of the object

    // --- Dynamic User Interaction Callbacks (Strictly Typed via nx_types.h) ---
    NX_ObjectCallback_t onPress;            // Triggered strictly when the component is pressed
    NX_ObjectCallback_t onRelease;          // Triggered strictly when the component is released

    // --- Application Context Hook ---
    void *userData;                         // Polymorphic pointer to bind custom application-specific logic
};

/*============================================================================*
 * Object Instance API Layer
 *============================================================================*/

/**
 * @brief Validates if the object instance supports a specific attribute.
 * @param[in] object Pointer to the target object instance.
 * @param[in] attribute The attribute token to verify.
 * @return true if supported, false if unauthorized or object is NULL.
 */
bool NX_ObjectHasAttribute(const NX_Object_t *object, NX_Attribute_t attribute);

/**
 * @brief Retrieves metadata for a specific attribute from the object's metaclass blueprint.
 * @param[in] object Pointer to the target object instance.
 * @param[in] attribute The attribute token to query.
 * @return Pointer to the static NX_AttributeInfo_t descriptor, or NULL if unauthorized.
 */
const NX_AttributeInfo_t *NX_ObjectGetAttribute(const NX_Object_t *object, NX_Attribute_t attribute);

/**
 * @brief Evaluates the component type classification of the given object.
 * @param[in] object Pointer to the target object instance.
 * @return The abstract component type enum, or NX_TYPE_UNKNOWN if invalid.
 */
NX_Type_t NX_ObjectType(const NX_Object_t *object);

/**
 * @brief Extracts the hardware component ID of the object instance.
 * @param[in] object Pointer to the target object instance.
 * @return Nextion component ID, or 0 if instance is NULL.
 */
uint8_t NX_ObjectId(const NX_Object_t *object);

/**
 * @brief Retrieves the string name structure wrapper of the object instance.
 * @param[in] object Pointer to the target object instance.
 * @return Pointer to the immutable NX_String wrapper, or NULL if instance is NULL.
 */
const NX_String_t *NX_ObjectName(const NX_Object_t *object);

/**
 * @brief Gets a pointer to the underlaying class blueprint used by the object.
 * @param[in] object Pointer to the target object instance.
 * @return Pointer to the immutable NX_ComponentClass_t, or NULL if invalid.
 */
const NX_ComponentClass_t *NX_ObjectComponent(const NX_Object_t *object);

/**
 * @brief Helper utility to instantly fetch the literal C-string name of an attribute if owned.
 * @param[in] object Pointer to the target object instance.
 * @param[in] attribute The target attribute token.
 * @return Direct pointer to the constant null-terminated string, or NULL if unauthorized/invalid.
 */
const char *NX_ObjectAttributeName(const NX_Object_t *object, NX_Attribute_t attribute);

#ifdef __cplusplus
}
#endif

#endif /* NX_OBJECT_H */
